# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155111
  start_block: 0
  contracts:
  - name: MediaAssetNFT
    address:
    - 0xf3C252022df94790aE4617C9058d9B3E5AEbB1E5
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: AssetUsed(uint256 indexed tokenId, address indexed user, uint256 paymentAmount)
    - event: BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)
    - event: DecryptionKeyReleased(uint256 indexed tokenId, address indexed buyer, string decryptionKey)
    - event: MediaAssetMinted(uint256 indexed tokenId, address indexed creator, string ipfsHash, string mediaType)
    - event: MetadataUpdate(uint256 _tokenId)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: RoyaltyPaid(uint256 indexed tokenId, address indexed recipient, uint256 amount)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
unordered_multichain_mode: true
preload_handlers: true
